---
- name: Using AS3 to deploy a configuration
  gather_facts: False
  hosts: bigip
  connection: "{{ ansible_connection }}"

  tasks:
    - name: test
      include_tasks: tasks.yaml
      loop: "{{ virtual_servers }}"

    # - name: Deploy CMS and OS application
    #   bigip_appsvcs_extension:
    #     content: "{{ lookup('template', './templates/cwp2_2.j2') }}"
    #     state: present
    #     provider: "{{ provider }}"
    #   loop: "{{ virtual_servers }}"