---
virtual_servers:
  - TENANT: "wordpress"
    VIP_ADDRESS: 
      - "10.19.128.0/21"
      - "10.19.136.0/21"
    PORTS: 
      - "8000"
  - TENANT: "swiiit"
    VIP_ADDRESS: 
      - "10.19.144.0/21"
      - "10.19.152.0/21"
    PORTS: 
      - "8300"
  - TENANT: "general_linux"
    VIP_ADDRESS: 
      - "10.19.24.0/21"
      - "10.19.32.0/21"
    PORTS: 
      - "3000"
      - "3100"
      - "5000"
      - "8080"
      - "4317"
      - "4318"
      - "9090"
